##########
# collectionbuilder-gh
# Jekyll Digital Collection Generator, designed for GitHub Pages
# https://github.com/CollectionBuilder/collectionbuilder-gh
##########

##########
# URL VARIABLES [optional if using GitHub Pages!]
#
# url is site domain, full URL to the production location of your collection
# on GitHub Pages follows the pattern username.github.io
#url: https://collectionbuilder.github.io 
# baseurl is path to location on the domain if necessary e.g. /digital/hjccc
# on GitHub Pages it is your github repository's name prefixed with a /
baseurl: /germantown-y
# location of code, the full url to your github repository
source-code: https://github.com/digbmc/germantown-y

##########
# SITE SETTINGS
#
# title of site appears in banner
title: Germantown YWCA
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: A Social History of a Building
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: The building at 5820 Germantown Avenue in Philadelphia once housed the Germantown YWCA Organization and served as a crucial community resource for nearly a century. Subsequently abandoned, it has become the site of a contentious political battle between many different interests including local residents, neighboring agencies and businesses, real estate developers and political agents. This exhibit aims to tell the histories of the building, the Germantown YWCA organization, and the community surrounding it.  
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: Bryn Mawr College Digital Scholarship

##########
# COLLECTION SETTINGS
#
# Set the metadata for your collection (the name of the csv file in your _data directory that describes the objects in your collection) 
# Use the filename of your CSV **without** the ".csv" extension! E.g. _data/demo-metadata.csv --> "demo-metadata"
metadata: germantown-y-metadata

##########
# Site/Organization Branding 
#   Uncomment these and enter information for your organization (replacing the CDIL links and name below) if you'd like to brand your site with a logo
#
# organization-name: "Center for Digital Inquiry and Learning (CDIL)"
# organization-link: https://cdil.lib.uidaho.edu/
# organization-logo-banner: https://cdil.lib.uidaho.edu/storying-extinction/assets/img/cdil.png
# organization-logo-nav: https://cdil.lib.uidaho.edu/assets/img/logo.png

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE, CITATION.cff, CODE_OF_CONDUCT.md, CONTRIBUTING.md]
# compress CSS output
sass:
  style: compressed

plugins:
  - jekyll-toc

collections: 
  exhibits:
    output: true 
    permalink: :collection/:name
defaults:
  - scope:
      path: ""
      type: "exhibits"
    values:
      layout: "exhibit-page"